[package]
name = "address-formatter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
csv = "1.3.1"
dotenv = "0.15.0"
lazy_static = "1.5.0"
odbc-api = "14.2.0"
regex = "1.11.1"
structopt = "0.3.26"
tokio = "1.47.0"
